### ISSUE TITLE
Temp clone of git remote branches are not in a repository

### ISSUE THREAD

**Issue by andrew-fennell** [sphinx-contrib/multiversion#109] opened 2023-12-19 15:41 UTC
There is an issue where remote branch configs cannot be loaded. After digging deeper into this issue, I found that there was a git command being ran, but it threw an error saying it was not in a git repository. This was in the `/tmp/...` directory created.

The issue seems to be that remote branches in `git.py` are created using the function `copy_tree(gitroot, src, dst, reference, sourcepath=".")`, which creates the git repository shown in the following code:

```
with tempfile.SpooledTemporaryFile() as fp:
        cmd = (
            "git",
            "archive",
            "--format",
            "tar",
            reference.commit,
            "--",
            sourcepath,
        )
        subprocess.check_call(cmd, cwd=gitroot, stdout=fp)
        fp.seek(0)
        with tarfile.TarFile(fileobj=fp) as tarfp:
            tarfp.extractall(dst)
```

This ultimately causes this error to be thrown in `main.py (line 245)`:

```logger.error(
                   "Failed load config for %s from %s",
                   gitref.refname,
                   confpath,
               )
```

---

A simple fix would be to add `git init` right after the first code snippet in `git.py`.

```
cmd = (
        "git",
        "init"
    )
    subprocess.check_call(cmd, cwd=dst)
```

**Comment by BurningEnlightenment** [comment] 2024-10-08 20:24
Duplicate of #17

**Closed** 2024-10-08 20:24 UTC
Labels: type:bug
