### ISSUE TITLE
failed to load config error

### ISSUE THREAD

**Issue by kne42** [sphinx-contrib/multiversion#44] opened 2020-09-10 21:12 UTC
Hi,

First of all thanks for putting in all the effort to develop/maintain this tool!

I was following your tutorial but was having trouble with some errors that look like this:
```
Failed load config for refs/heads/master from /var/folders/7n/d1xn4hp17sz58sf0rckg7jj40000gp/T/tmp0ximpy89/b1d75c24e401227ba3bb17aa9a6f71dd21eef641/docs/source
```

I've left it with default settings as well as trying the ones below but it keeps coming up with the same error:
```
smv_tag_whitelist = r'^v\d+\.\d+$'
smv_branch_whitelist = r'^master$'
smv_remote_whitelist = r'^upstream$'
```

I would greatly appreciate your help in debugging this!

Thanks :)

**Comment by haishiro** [comment] 2020-09-16 15:19
In my case, I'm getting this error because the sphinx doc folder in our project is excluded from archives.

We have a .gitattributes file which excludes all docs using `export-ignore`. This is so that we don't include the docs in our releases. sphinx-multiversion uses `git archive` when making the copy and so it doesn't include these files during the build.
https://github.com/Holzhaus/sphinx-multiversion/blob/76dba73d0d4bebee3906176ed3f1f7dc58baec81/sphinx_multiversion/git.py#L149-L163

**Comment by BurningEnlightenment** [comment] 2024-10-06 17:11
Duplicate of #17

If you think that this is not the case, feel free to reopen and provide us with a reprex (reproducing example) or if possible a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example).

**Closed by BurningEnlightenment** 2024-10-06 17:11 UTC
