### ISSUE TITLE
'smv_released_pattern' examples should start with 'refs/'

### ISSUE THREAD

**Issue by LewisGaul** [sphinx-contrib/multiversion#66] opened 2021-01-24 21:54 UTC
The example regex patterns for `smv_released_pattern` start with `^tags/`, `^heads/` and `^remotes/`, however this appears to be missing the required `refs/` at the start. I was seeing everything failing to match until I made it `^refs/tags/.*$`.

See https://holzhaus.github.io/sphinx-multiversion/master/configuration.html.

Thanks for the tool :)

**Comment by tonywhittam** [comment] 2022-01-31 15:08
Thanks @LewisGaul. I was having this issue and confirm that it works exactly the way you said.

**Comment by BurningEnlightenment** [comment] 2024-10-06 17:53
Duplicate of #59

**Closed** 2024-10-07 09:30 UTC
